### ISSUE TITLE
Dynamically add options to minimalect based on other select?

### ISSUE THREAD

**Issue by fearghalmurphy** [groenroos/minimalect#45]
So I'm trying to chain a number of select menus together. Ie. Selecting a option will dynamically populate another select. Standard select boxes, easy peasy. But what about dynamically populating a minimalect-ed select?

**Comment by pipsmithe** [comment]
I have just been experiencing the same problem as Fearghal, above, on one of my sites; when select box is dynamically edited (whether by jquery .html, or .append), any selection of minimalect options isn't 'held'. In Chrome, FF, and IE.

Fearghal - did you have any luck in solving this?

**Comment by pipsmithe** [comment]
Ah, i see logged in issue #46, but unfortunately no solution?
