### ISSUE TITLE
TypeError: this.options is undefined

### ISSUE THREAD

**Issue by oshihirii** [groenroos/minimalect#60]
I am wanting to enable groups in the options list.  

In my script I append the following html to an element and then call `minimalect` afterwards (i've left it as a string in this snippet in case the format has caused the issue):

    <select id=\"my_select\"><optgroup label=\"my playlists\"><option selected=\"selected\" value=\"v1\">v1</option><option value=\"v2\">v2</option><option value=\"v3\">v3</option><option value=\"v4\">v4</option><option value=\"v5\">v5</option><option value=\"v6\">v6</option><option value=\"v7\">v7</option><option value=\"v8\">v8</option><option value=\"v9\">v9</option></optgroup></select>

The HTML produced by the `append` is correctly formed ie:

    <select id="my_select">
    <optgroup label="my playlists">
    <option selected="selected" value="v1">v1</option>
    <option value="v2">v2</option>
    <option value="v3">v3</option>
    <option value="v4">v4</option>
    <option value="v5">v5</option>
    <option value="v6">v6</option>
    <option value="v7">v7</option>
    <option value="v8">v8</option>
    <option value="v9">v9</option>
    </optgroup>
    </select>

I'm getting this error in Firebug:

    TypeError: this.options is undefined (line 317, col 5)

Line:  https://github.com/groenroos/minimalect/blob/master/jquery.minimalect.js#L321

And it halts the page, `minimalect` and other scripts loading.  

    $("#my_select").minimalect({placeholder:"choose playlist", searchable: false});

The plugin works if there is no `<optgroup>`.  

Using `jquery.minimalect.js 0.9`, same error in `jquery.minimalect.min.js 0.8b`.

**Comment by oshihirii** [comment]
**Update**

Weird, I tried using the js file used on the demo:

http://groenroos.github.io/minimalect/javascripts/minimalect.js?c=201305202005

And the functionality works.

**Comment by groenroos** [comment]
The demo site still uses version 0.8 instead of the 0.9.0 currently in the repo.

I believe @patrickgalbraith fixed this particular bug in f3c9f8c. Have you tried re-downloading the non-minified version from the repo?

**Comment by oshihirii** [comment]
My first test a couple of hours ago was with `0.9` version currently in repo, but I just did what you suggested and re-downloaded it and it fixed the issue.
